# Generated by Django 4.0.4 on 2022-06-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip_no',
        ),
        migrations.RemoveField(
            model_name='people',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
